services:

  backend:
    build: ./backend
    ports:
      - "3006:3001"
    environment:
      DATABASE_URL: postgresql://projeto6_user:senha_projeto6@cin-postgres:5432/projeto6_db
      JWT_SECRET: nutricao_jwt_secret_2026
      JWT_EXPIRES_IN: 7d
      PORT: 3006
    networks:
      - cin_proxy

  frontend:
    build:
      context: ./frontend
    container_name: projeto-2-frontend
    volumes:
      - /opt/docker/frontends/projeto2:/output
    depends_on:
      - backend
    restart: "no"
    environment:
      VITE_BASE: /nutricao/
      VITE_API_PROXY: http://backend:3001
      VITE_API_URL: http://vm-clindig.cin.ufpe.br/nutricao
    networks:
      - cin_proxy

networks:
  cin_proxy:
    external: true